version: "3"

services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    env_file:
      - ./db/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

  api:
    build: ./blabla_hors
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: /api/entrypoint.sh
    ports:
      - 8000:8000
    volumes:
      - ./blabla_hors:/api

volumes:
  postgres:
