# Generated by Django 4.1 on 2022-08-31 19:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('animals_num', models.PositiveIntegerField(default=0)),
                ('people_num', models.PositiveIntegerField(default=0)),
                ('animals_price', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('person_price', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animals_num', models.PositiveIntegerField(default=0)),
                ('people_num', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CANCELED', 'CANCELED'), ('APPROVED', 'APPROVED'), ('REFUSED', 'REFUSED')], default='PENDING', max_length=15)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.route')),
            ],
        ),
        migrations.AddConstraint(
            model_name='passenger',
            constraint=models.UniqueConstraint(fields=('route', 'passenger'), name='unique-constraint'),
        ),
    ]
