# Generated by Django 4.1 on 2022-08-27 21:30

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_useropts_access_token_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='id',
        ),
        migrations.RemoveField(
            model_name='useropts',
            name='access_token',
        ),
        migrations.AddField(
            model_name='route',
            name='animals_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='animals_price',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='route',
            name='people_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='person_price',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='route',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
